# Generated by Django 5.0.9 on 2026-01-31 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('compositor', models.CharField(blank=True, max_length=200)),
                ('duracao', models.TimeField(blank=True, null=True)),
                ('link_cifra', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'db_table': 'musicas',
            },
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('instrumento_principal', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Músico',
                'verbose_name_plural': 'Músicos',
                'db_table': 'musicos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_evento', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('repertorio', models.ManyToManyField(blank=True, related_name='eventos', to='core.musica')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_no_evento', models.CharField(blank=True, max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='core.evento')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='core.musico')),
            ],
            options={
                'verbose_name': 'Escalas',
                'db_table': 'escalas',
                'unique_together': {('musico', 'evento')},
            },
        ),
    ]
