# Generated by Django 5.0.9 on 2026-02-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='compositor',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='nome',
        ),
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='link_youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='tom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
