# Generated by Django 5.0.9 on 2026-02-12 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_musica_compositor_remove_musica_duracao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['evento__data_evento'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_evento'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='musico',
            options={'ordering': ['nome'], 'verbose_name': 'Músico', 'verbose_name_plural': 'Músicos'},
        ),
        migrations.AddField(
            model_name='escala',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escala',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('CULTO', 'Culto'), ('CONFERENCIA', 'Conferência'), ('CELULA', 'Célula'), ('ESPECIAL', 'Especial')], default='CULTO', max_length=20),
        ),
        migrations.AddField(
            model_name='musico',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musico',
            name='data_fim_inatividade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musico',
            name='data_inicio_inatividade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musico',
            name='motivo_inatividade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='musico',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado Temporariamente')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='escala',
            name='instrumento_no_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instrumento'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='core.musico'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musico',
            name='instrumento_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicos', to='core.instrumento'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
