# Generated by Django 5.0.9 on 2026-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_escala_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
