# Generated by Django 5.0.9 on 2026-02-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_musico_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token FCM'),
        ),
    ]
