# Generated by Django 5.0.9 on 2026-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_musico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musico',
            name='email',
        ),
        migrations.AddField(
            model_name='musico',
            name='tipo_usuario',
            field=models.CharField(choices=[('MUSICO', 'Músico'), ('LIDER', 'Líder'), ('ADMIN', 'Administrador')], default='MUSICO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
