# Generated by Django 5.0.9 on 2026-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_musico_email_musico_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='role',
            field=models.CharField(choices=[('MUSICO', 'Músico'), ('LIDER', 'Líder')], default='MUSICO', max_length=20),
        ),
    ]
