# Generated by Django 5.0.9 on 2026-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_musico_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='precisa_mudar_senha',
            field=models.BooleanField(default=True, help_text='True se o usuário precisa mudar a senha no próximo login'),
        ),
    ]
