# Generated by Django 5.1.15 on 2026-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adicionar_artistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='data_hora_ensaio',
            field=models.DateTimeField(blank=True, help_text='Data e hora do ensaio para este evento (opcional)', null=True, verbose_name='Data e Hora do Ensaio'),
        ),
    ]
