# Generated by Django 5.1.15 on 2026-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_data_hora_ensaio_to_escala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='data_hora_ensaio',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_hora_ensaio',
            field=models.DateTimeField(blank=True, help_text='Data e hora do ensaio para este evento (opcional)', null=True, verbose_name='Data e Hora do Ensaio'),
        ),
    ]
