# Generated by Django 5.1.15 on 2026-02-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_move_data_hora_ensaio_escala_para_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_feitos', to='core.musico')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_performance', to='core.evento')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_performance', to='core.musica')),
            ],
            options={
                'verbose_name': 'Comentário de Performance',
                'verbose_name_plural': 'Comentários de Performance',
                'db_table': 'comentarios_performance',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReacaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='core.comentarioperformance')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_dadas', to='core.musico')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'db_table': 'reacoes_comentario',
                'unique_together': {('comentario', 'musico')},
            },
        ),
    ]
