# Generated by Django 5.1.15 on 2026-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_comentario_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='conteudo_cifra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
