# Generated by Django 5.1.15 on 2026-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_musica_conteudo_cifra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='instrumento_no_evento',
        ),
        migrations.AddField(
            model_name='escala',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, related_name='escalas', to='core.instrumento', verbose_name='Instrumentos no evento'),
        ),
    ]
